{
  "compute_environment": "LOCAL_MACHINE",
  "debug": false,
  "distributed_type": "MULTI_GPU",
  "downcast_bf16": false,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "bf16",
  "num_machines": 1,
  "num_processes": 4,
  "rdzv_backend": "c10d",
  "same_network": True,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}
